project:
  type: book

book:
  title: "NEON Ecological Forecasting Challenge"
  author: "Ecological Forecasting Initative Research Coordination Network"
  date: now
  logo: images/EFI_Logo-1.jpg
  chapters:
    - index.qmd
    - Aquatics.qmd
    - Terrestrial.qmd
    - Ticks.qmd
    - Phenology.qmd
    - Beetles.qmd
    - Participation.qmd
    - Submission-Instructions.qmd
    - Metadata.qmd
    - Evaluation.qmd
    - Shared-Forecast-Drivers.qmd
    - WorkflowExample.qmd
    - Helpful-Functions.qmd
    - UseInCourse.qmd
    - FAQ.qmd


bibliography: references.bib

format:
  html:
    theme: cosmo

editor: visual

