# Workflow derived from https://github.com/r-lib/actions/tree/master/examples
# Need help debugging build failures? Start at https://github.com/r-lib/actions#where-to-find-help
on:
  push:
    branches:
      - main
  workflow_dispatch:

name: Update & Deploy dashboard
jobs:
  docker:
    runs-on: ubuntu-latest
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
    container: rocker/geospatial:latest
    steps:
      - run: git config --system --add safe.directory '*'

      - uses: actions/checkout@v3
        with:
           fetch-depth: 0
           set-safe-directory: '*'
   

      - uses: quarto-dev/quarto-actions/setup@v2
        with:
          version: 1.4.146
          
      - name: install R packages
        shell: Rscript {0} 
        run: install.packages(c("scoringRules"))
          
      - name: Render book to all format
        # Add any command line argument needed
        run: |
          quarto install tool tinytex
          quarto render
          cp -r _book/* docs/.
          
      - name: Commit results
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add docs/* 
          git commit docs/* -m 'Re-build site' || echo "No changes to commit"
          git push https://${GITHUB_PAT}:${GITHUB_PAT}@github.com/${GITHUB_REPOSITORY}
          
